### ISSUE TITLE
HTTP 400 for a simple text POST

### ISSUE THREAD

**Issue by ianmclaughlin** [movsky/bluesky-api-php#4]
First, thanks for writing this. It looks nice and simple to use.

```
try {
    $bluesky_api = new \Mov\BlueskyApi\BlueskyApi();
    trigger_error("instantiated API");
    $bluesky_api->authenticate($bsky_handle, $bsky_password);
    trigger_error("authenticated");
    $bluesky_api->post("test skeet",[], ['en']);
    trigger_error("posted");
} catch (Exception $e) {
    trigger_error('Bsky exception ' . $e->getMessage() . " Trace=" . $e->getTraceAsString(), E_USER_NOTICE);
}
```

causes: 
[29-Nov-2023 09:16:46 Europe/London] PHP Notice:  instantiated API in <source file> on line 18
[29-Nov-2023 09:16:47 Europe/London] PHP Notice:  authenticated in <source file> on line 20
[29-Nov-2023 09:16:47 Europe/London] PHP Notice:  Bsky exception HTTP/2 400  returned for "https://bsky.social/xrpc/com.atproto.repo.createRecord". Trace=
#0 <>vendor/symfony/http-client/Response/TransportResponseTrait.php(131): Symfony\Component\HttpClient\Response\CurlResponse->checkStatusCode()
#1 <>vendor/symfony/http-client/Response/CurlResponse.php(243): Symfony\Component\HttpClient\Response\CurlResponse->doDestruct()
#2 <>vendor/symfony/http-client/CurlHttpClient.php(317): Symfony\Component\HttpClient\Response\CurlResponse->__destruct()
#3 <>vendor/mov/php-bluesky/BlueskyApi.php(86): Symfony\Component\HttpClient\CurlHttpClient->request()
#4 <source file>(21): Mov\BlueskyApi\BlueskyApi->post()
#5 {main} in <source file> on line 24

**Comment by movsky** [comment]
Thanks for letting me know. There was an error while posting with an empty array for $embed. I just provided a fix, please update and it should work as expected

**Comment by ianmclaughlin** [comment]
That fix works, thanks. Now I just need to wait for Packagist to catch up with the hotfix

**Comment by movsky** [comment]
Should be available now

**Comment by ianmclaughlin** [comment]
Yes, thank you!
